config:
  credentials:
  - id: synergy_dockerhub_bot_pass
    password_var: JPL_DOCKERPASS
    username_var: JPL_DOCKERUSER
  project_repos:
    github.com/EOSC-synergy/saps-catalog:
      branch: develop
      repo: https://github.com/EOSC-synergy/saps-catalog
    github.com/EOSC-synergy/saps-common:
      branch: develop
      repo: https://github.com/EOSC-synergy/saps-common
    github.com/EOSC-synergy/saps-scheduler:
      branch: develop
      repo: https://github.com/EOSC-synergy/saps-scheduler
environment:
  JPL_DOCKERPUSH: scheduler-build
sqa_criteria:
  qc_style:
    repos:
      github.com/EOSC-synergy/saps-scheduler:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-copper-otter.sh
        container: scheduler-testing
timeout: 600
